version: '3.7'
services:  
  express:
    build: ./express
    ports:
      - "3000:3000"
    volumes:
      - ./express/src:/var/www/src:delegated
    networks:
      - data
      - front
  mysql_db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Totally_Secure
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydb_user
      MYSQL_PASSWORD: mydb_password        
    networks: 
      - data
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
    ports:
      - 8080:8080
    networks:
      - data
networks:
  data:
  front:
volumes:
  mysql-data: